### ISSUE TITLE
MIPS MTI 工具链托管

### ISSUE THREAD

**Issue by eatradish** [github0null/eide-resource#149]
我注意本仓库托管了许多 EIDE 依赖工具链的下载链接，可否在此仓库托管 MIPS MTI 的下载，以便将该工具链纳入下载菜单当中？

我们最新的的工具链包（对应 Windows 和 Linux）可从此处下载：https://repo.oss.cipunited.com/mips-toolchain-cip/20230510/

**Comment by github0null** [comment]
已经在邮件中提到过了

由于工具链比较大，后面我会增加到这个仓库下，效果是一样的：

https://github.com/github0null/eide_default_external_tools_index/blob/master/index.json
